// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    partial class FirstAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            ID = 2,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            ID = 3,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            ID = 4,
                            Author = "John Steinbeck",
                            Title = "Of Mice and Men",
                            YearPublished = 1937
                        },
                        new
                        {
                            ID = 5,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            ID = 6,
                            Author = "J.D. Salinger",
                            Title = "The Catcher in the Rye",
                            YearPublished = 1951
                        },
                        new
                        {
                            ID = 7,
                            Author = "Aldous Huxley",
                            Title = "Brave New World",
                            YearPublished = 1932
                        },
                        new
                        {
                            ID = 8,
                            Author = "Ray Bradbury",
                            Title = "Fahrenheit 451",
                            YearPublished = 1953
                        },
                        new
                        {
                            ID = 9,
                            Author = "J.R.R. Tolkien",
                            Title = "The Hobbit",
                            YearPublished = 1937
                        },
                        new
                        {
                            ID = 10,
                            Author = "J.R.R. Tolkien",
                            Title = "The Lord of the Rings",
                            YearPublished = 1954
                        },
                        new
                        {
                            ID = 11,
                            Author = "Paulo Coelho",
                            Title = "The Alchemist",
                            YearPublished = 1988
                        },
                        new
                        {
                            ID = 12,
                            Author = "George Orwell",
                            Title = "Animal Farm",
                            YearPublished = 1945
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
